macos_instance:
  image: big-sur-base

task:
  timeout_in: 120m
  script:
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/ya0kfgwjkxc0wde/rkprime.21.02.24.codi.vore.sweeping.up.with.her.big.natural.tits.mp4"
  rendering_script:
    - ffmpeg -i "rkprime.21.02.24.codi.vore.sweeping.up.with.her.big.natural.tits.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Codi Vore - Sweeping Up With Her Big Natural Tits" -preset veryfast -pix_fmt yuv420p10le codi.vore.sweeping.up.with.her.big.natural.tits.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "codi.vore.sweeping.up.with.her.big.natural.tits.x265.mp4"
