macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: nl20.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/' --header 'Upgrade-Insecure-Requests: 1' 'https://nl20.seedr.cc/ff_get/886975516/FC2-PPV-1742130.mp4?st=XA_LaDC3BeRdnIbDX8dvoA&e=1617820858' --out 'FC2-PPV-1742130.mp4'"
  rendering_script:
    - ffmpeg -i "FC2-PPV-1742130.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="FC2 PPV 1742130" -preset veryfast -pix_fmt yuv420p10le FC2-PPV-1742130.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "FC2-PPV-1742130.x265.mp4"
