macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/xre2nuftlywyyrb/River.Where.the.Moon.Rises.E09-E10.210301.720p-NEXT.mp4"
  rendering_script:
    - ffmpeg -i "River.Where.the.Moon.Rises.E09-E10.210301.720p-NEXT.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="River Where The Moon Rises Episode 05" -preset veryfast -pix_fmt yuv420p10le 05.mkv
    - ls -hal
  binaries_artifacts:
    path: "05.mkv"
