macos_instance:
  image: big-sur-base

task:
  timeout_in: 120m
  script:
    - brew install ffmpeg aria2
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 'https://www.dropbox.com/s/dl/p07qkfoqvxiicmu/Tom.And.Jerry.2021.1080p.WEBRip.x264.AAC5.1-%5BYTS.MX%5D.mp4'"
    - ffmpeg -i "Tom.And.Jerry.2021.1080p.WEBRip.x264.AAC5.1-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Tom And Jerry 2021" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 Tom.And.Jerry.2021.1080p.WEBRip.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Tom.And.Jerry.2021.1080p.WEBRip.x265.mp4"
