macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: fr16.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/' --header 'Upgrade-Insecure-Requests: 1' 'https://fr16.seedr.cc/ff_get/884847010/The.Penthouse.S02E13.1080p.WEB-DL.H264.AAC-AppleTor.mp4?st=v97XWzJ3iOX65CFxMhkrMA&e=1617557948' --out 'The.Penthouse.S02E13.1080p.WEB-DL.H264.AAC-AppleTor.mp4'"
  rendering_script:
    - ffmpeg -i "The.Penthouse.S02E13.1080p.WEB-DL.H264.AAC-AppleTor.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="The Penthouse Season 2 Episode 13" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 The.Penthouse.S02E13.720p.WEB-DL.H265.AAC-AppleTor.mkv
    - ls -hal
  binaries_artifacts:
    path: "The.Penthouse.S02E13.720p.WEB-DL.H265.AAC-AppleTor.mkv"

