macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 'https://www.dropbox.com/s/dl/cx63t24vrq98wx4/SAS.Red.Notice.2021.1080p.WEBRip.x264.AAC5.1-%5BYTS.MX%5D.mp4'"
  rendering_script:
    - ffmpeg -i "SAS.Red.Notice.2021.1080p.WEBRip.x264.AAC5.1-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="SAS Red Notice" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 SAS.Red.Notice.2021.720p.WEBRip.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "SAS.Red.Notice.2021.720p.WEBRip.x265.mp4"
