macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: de19.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/165050972' --header 'Upgrade-Insecure-Requests: 1' 'https://de19.seedr.cc/ff_get/878077539/Happiest.Season.2020.1080p.WEBRip.x264.AAC5.1-[YTS.MX].mp4?st=j-nkWcu61QvkPhFgIcywQA&e=1616856718' --out 'Happiest.Season.2020.1080p.WEBRip.x264.AAC5.1-[YTS.MX].mp4'"
  rendering_script:
    - ffmpeg -i "Happiest.Season.2020.1080p.WEBRip.x264.AAC5.1-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Happiest Season 2020" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 Happiest.Season.2020.720p.WEBRip.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Happiest.Season.2020.720p.WEBRip.x265.mp4"

