macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://tigefa.my.id/Running.Man.E548.210328.720p-NEXT.mkv"
  rendering_script:
    - ffmpeg -i "Running.Man.E548.210328.720p-NEXT.mkv" -threads 16 -c:v libx265 -c:a copy -metadata title="Running Man Episode 548" -preset veryfast -pix_fmt yuv420p10le 548.mkv
    - ls -hal
  binaries_artifacts:
    path: "548.mkv"

