macos_instance:
  image: big-sur-base

task:
  timeout_in: 120m
  script:
    - brew list
    - brew install ffmpeg aria2
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/llwzvv3wnufck8x/Sisyphus.The.Myth.S01E04.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv"
    - ffmpeg -i "Sisyphus.The.Myth.S01E04.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv" -threads 16 -c:v libx265 -c:a copy -c:s copy -metadata title="Sisyphus The Myth Episode 4" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 04.mkv
    - ls -hal
  binaries_artifacts:
    path: "04.mkv"
