macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
    - brew update --force
    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/yb4dd93kv646jsb/L.U.C.A.The.Beginning.E12.END.210309.720p-NEXT.mp4"
  rendering_script:
    - ffmpeg -i "L.U.C.A.The.Beginning.E12.END.210309.720p-NEXT.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="L.U.C.A The Beginning Episode 12" -preset veryfast -pix_fmt yuv420p10le 12.mkv
    - ls -hal
  binaries_artifacts:
    path: "12.mkv"
