macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/4wkmki98f2flgmz/Vincenzo.S01E13.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv"
  rendering_script:
    - ffmpeg -i "Vincenzo.S01E13.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv" -threads 16 -c:v libx265 -c:a copy -metadata title="Vincenzo Episode 13" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 13.mkv
    - ls -hal
  binaries_artifacts:
    path: "13.mkv"

