container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://yts.mx/torrent/download/F5B3839C4E714966DB0F6F1738D493D16BCACBF5"
#    - "aria2c --check-certificate=false --header 'Host: fr14.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/140882827' --header 'Upgrade-Insecure-Requests: 1' 'https://fr14.seedr.cc/ff_get/731225376/Rogue.2020.720p.BluRay.x264.AAC-[YTS.MX].mp4?st=TwWpl9Az0W-gindIWqk7RA&e=1598377608' --out 'Rogue.2020.720p.BluRay.x264.AAC-[YTS.MX].mp4'"
    - ffmpeg -i "One Night In Bangkok (2020) [720p] [WEBRip] [YTS.MX]/One.Night.In.Bangkok.2020.720p.WEBRip.x264.AAC-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="One Night In Bangkok 2020" -preset veryfast One.Night.In.Bangkok.2020.720p.WEBRip.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "One.Night.In.Bangkok.2020.720p.WEBRip.x265.mp4"
