macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://tigefa.my.id/JUL-528.mp4"
  rendering_script:
    - ffmpeg -i "JUL-528.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Kyoko Ichikawa" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 JUL-528.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "JUL-528.x265.mp4"

