container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
#    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://yts.mx/torrent/download/6F8EEF779145DA6ECC61AFF51FFA44A23B803CEC"
    - "aria2c --check-certificate=false --header 'Host: de9.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/143666177' --header 'Upgrade-Insecure-Requests: 1' 'https://de9.seedr.cc/ff_get/748461226/Triple.9.2016.720p.BluRay.x264-[YTS.AG].mp4?st=V3GlKDTVdkmk3Xs87wfIsA&e=1600628596' --out 'Triple.9.2016.720p.BluRay.x264-[YTS.AG].mp4'"
    - ffmpeg -i "Triple.9.2016.720p.BluRay.x264-[YTS.AG].mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Triple 9 2016" -preset veryfast Triple.9.2016.720p.BluRay.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Triple.9.2016.720p.BluRay.x265.mp4"
