macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --file-allocation=none --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/ygfcy8bp9nb890d/Joseon.Exorcist.S01E02.1080p.WEB-DL.H264.AAC-AppleTor.mp4"
  rendering_script:
    - ffmpeg -i "Joseon.Exorcist.S01E02.1080p.WEB-DL.H264.AAC-AppleTor.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Joseon Exorcist Episode 2" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 02.mkv
    - ls -hal
  binaries_artifacts:
    path: "02.mkv"
