macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/wqxvcsee70o55v9/PGD-777_uncensored.mp4"
  rendering_script:
    - ffmpeg -i "PGD-777_uncensored.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Anri Okita" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 PGD-777.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "PGD-777.x265.mp4"
