macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: fr16.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/164917268' --header 'Upgrade-Insecure-Requests: 1' 'https://fr16.seedr.cc/ff_get/877191288/Sisyphus.The.Myth.S01E12.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv?st=p7hZAJI5YlcWjb-BhYyehA&e=1616775197' --out 'Sisyphus.The.Myth.S01E12.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv'
  rendering_script:
    - ffmpeg -i "Sisyphus.The.Myth.S01E12.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv" -threads 16 -c:v libx265 -c:a copy -metadata title="Sisyphus The Myth Episode 12" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 12.mkv
    - ls -hal
  binaries_artifacts:
    path: "12.mkv"

