container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://onejav.com/torrent/bacn013/download/719469/onejav.com_bacn013.torrent"
#    - "aria2c --check-certificate=false --header 'Host: de12.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/138086876' --header 'Upgrade-Insecure-Requests: 1' 'https://de12.seedr.cc/ff_get/714599722/May.The.Devil.Take.You.2018.720p.WEBRip.x264-[YTS.AM].mp4?st=HSIagfbJX7TY_GHnCDTGCQ&e=1596132890' --out 'May.The.Devil.Take.You.2018.720p.WEBRip.x264-[YTS.AM].mp4'"
    - ffmpeg -i "BACN-013.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Sacchan Sachiko" -preset veryfast -s 960x540 BACN-013-x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "BACN-013-x265.mp4"
