macos_instance:
  image: big-sur-xcode-12.4

task:
  timeout_in: 120m
  script:
#    - brew update --force
#    - brew list --formula
    - brew install ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/9bae4olp16mddhy/The.Penthouse.S02E08.1080p.WEB-DL.H264.AAC-AppleTor.mp4"
  rendering_script:
    - ffmpeg -i "The.Penthouse.S02E08.1080p.WEB-DL.H264.AAC-AppleTor.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="The Penthouse Season 2 Episode 8" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 The.Penthouse.S02E08.720p.WEB-DL.H265.AAC-AppleTor.mkv
    - ls -hal
  binaries_artifacts:
    path: "The.Penthouse.S02E08.720p.WEB-DL.H265.AAC-AppleTor.mkv"
